### ISSUE TITLE
[#002] フルスクリーンにしたとき、divが消える

### ISSUE THREAD

**Issue by aidmiya** [kure-kosen/kure_kosen_map#2]
マップページで、フルスクリーン表示にすると、divで作ってみたボタンやdivで作ってみたメニューが消えた。
たぶんdivは全部消える。

**Comment by aidmiya** [comment]
【追記】
メニューもだけど検索ボックスも消える。
検索ボックスが消えるとなるとなかなかにダサいから切実な問題になりつつある…

**Comment by kobakazu0429** [comment]
@aidmiya 
```
    <div id="map" class="map">
     <form action="#" method="post" class="search" style="z-index: 1;">
       <div class="search-box">
        <input type="text" name="q">
        <input type="reset" value="&#61453;" class="fa">
       </div>
      </form>
    </div>
```

フルスクリーンにしたときに表示したいものをdivの中に入れてやると大丈夫みたい
`z-index`をつけないと下に消えるから注意

**Comment by aidmiya** [comment]
やってみる。

**Comment by aidmiya** [comment]
#mapの中にまとめて入れて見たけど、フルスクリーンにした後すぐに消え、フルスクリーンを解除しても復活しなくなった。
z-indexをつけても変化なしだった。
Chromiumに至っては最初から表示されん。
どうしようかの

**Comment by aidmiya** [comment]
フルスクリーンにした後じゃなくて、ページを(地図を)ロードしたらフェードアウトする形で消えた。
この方法じゃだめかも？
それとも俺の書き方が間違っているのか。

**Comment by kobakazu0429** [comment]
@aidmiya 
[[fix]fullscreen](https://github.com/kure-kosen/kure_kosen_map/commit/21e561e952f074f782ffaf5e339bb2ada102e234)
多分`<div class="fullscreenlayer">`の中に書けば消えないはず
```html
    <div id="fullscreen" class="fullscreen">
      <div id="map" class="map"></div>
      <div class="fullscreenlayer">
        <button class="hoge">aa</button>
      </div>
    </div>
```

これでやってみて

**Comment by aidmiya** [comment]
やってみたけど状況は何も変わらず治らん。
.fullscreen,#fullscreen,.fullscreenlayerには何もスタイルが適用されてないみたいだけど(JSは調べてない)、何かインクルード(読み込み)しないといけないファイルはある?

**Comment by kobakazu0429** [comment]
@aidmiya 
コミットの内容しっかり見て…
変更したファイルは

assets/css/map.css
assets/js/main.js
map.html
の三つ

**Comment by aidmiya** [comment]
「[fix]fullscreen」ってのはコミット差分へのリンクだったのか。
よくわからなかったから触ってなかった。すまぬ

**Comment by aidmiya** [comment]
再度試してみたけど、今度はレイアウトが大幅に狂ったで。
コミットはしないほうが良いんだろうから、画像を載せとく。

**Comment by aidmiya** [comment]
![image](https://user-images.githubusercontent.com/31529568/34917107-41c82be4-f985-11e7-92cd-8e83a60d7c88.png)
ちょっと今日の作業はこのへんにさせて。

**Comment by aidmiya** [comment]
こばがいじくって解決したので閉じます。
